version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: '⬆️ deps:'
      prefix-development: '⬆️ deps(dev):'
    assignees:
      - filiptronicek
      - bigint
    reviewers:
      - filiptronicek
      - bigint
    open-pull-requests-limit: 69
    rebase-strategy: auto
    labels:
      - automerge
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - automerge
