image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup
    before: redis-server &
    init: |
      yarn install --frozen-lockfile --silent --network-timeout 100000
      cp .env.example .env
      echo -e "\n\nNEXTAUTH_SECRET=\"$(head -1 <(fold -w 20 <(tr -dc 'a-zA-Z0-9' </dev/urandom)))\"" >>.env
      gp await-port 3306
      yarn prisma:migrate
      yarn prisma:seed

    command: |
      export BASE_URL=`gp url 3000`
      export NEXTAUTH_URL=`gp url 3000`
      yarn dev

  - name: Prisma Studio
    command: |
      gp await-port 3000
      BROWSER=none yarn prisma studio

ports:
  - port: 3000 # Web app
    onOpen: notify
    visibility: public
  - port: 5555 # Prisma Studio
    onOpen: ignore
    visibility: public
  - port: 3306 # MySQL
    onOpen: ignore
  - port: 6379 # Redis
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - mikestead.dotenv
    - graphql.vscode-graphql
    - christian-kohler.npm-intellisense
    - esbenp.prettier-vscode
    - prisma.prisma
    - eamodio.gitlens
    - pflannery.vscode-versionlens
    - wix.vscode-import-cost
    - formulahendry.auto-close-tag
    - github.github-vscode-theme
    - bradlc.vscode-tailwindcss
    - bierner.markdown-preview-github-styles
    - editorconfig.editorconfig
    - cweijan.vscode-redis-client
    - https://github.com/wix/vscode-glean/releases/download/v5.2.2/vscode-glean.vsix
