name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '14.x'
          cache: 'yarn'

      - name: Count Lines of Code (cloc)
        uses: djdefi/cloc-action@main

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CI: true
