name: auto-merge

on:
  pull_request:
    types:
      - opened
    branches:    
      - 'dependabot/**'
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            automerge
